version: "3.8"
services:
  web:
    image: node:14
    ports:
      - 8081:8080
    volumes:
      - type: bind
        source: .
        target: /app
    working_dir: /app
    entrypoint:
      - npm
      - run
      - start
    environment:
      - SERVICE_NAME=web
  web2:
    image: node:14
    ports:
      - 8081:8080
    volumes:
      - type: bind
        source: .
        target: /app
    working_dir: /app
    entrypoint:
      - npm
      - run
      - start
    environment:
      - SERVICE_NAME=web2